pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/multimall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username:  root
    password:  root
